config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#home'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :cost, :origin, :presence => true
  scope :recently_added, -> { order(created_at: :desc).limit(3) }
  scope :made_in_usa, -> { where(origin: "USA") }
  scope :most_reviews, -> {(
    select("products.*, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count desc")
    .first
    )}

  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :author, :content_body, :rating, :product_id, :presence => true
  validates :rating, numericality: { greaten_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :content_body, length: { within: 50..250 }

  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def home
    @most_reviewed = Product.most_reviews
    @usa_made = Product.made_in_usa
    @recent_products = Product.recently_added
  end

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product has been added!"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product has been updated!"
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product has been deleted!"
    redirect_to products_path
  end


private
  def product_params
    params.require(:product).permit(:name, :cost, :origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review has been update!"
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating, :product_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <h3>Please fix these errors:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
           <%= link_to "Mario's foods", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li> <%= link_to "Add Product", new_product_path %> </li>
          <li> <%= link_to "All Products", products_path %> </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <% if flash[:notice] != nil %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "control-label"%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :cost, class: "control-label" %>
    <%= f.text_field :cost, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :origin, class: "control-label" %>
    <%= f.text_field :origin, class: "form-control" %>
  </div>
  <%= f.submit class: "btn" %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %> </h1>

<%= render 'form' %>

app/views/products/home.html.erb
<div class="welcome">
  <h1>Welcome to Mario's Foods!</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="product-panel panel panel-default">
        <div class="panel-heading">
          <h3>Most Reviewed Product</h3>
        </div>
        <div class="panel-body">
          <% if @most_reviewed %>
            <h4> <%= link_to @most_reviewed.name, product_path(@most_reviewed), class: 'product' %> </h4>
          <% else %>
          <h4>There currently isn't a most reviewed product.</h4>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="product-panel panel panel-default">
        <div class="panel-heading">
          <h3>Recently Added</h3>
        </div>
        <div class="panel-body">
          <% @recent_products.each do |product| %>
            <h4><%= link_to product.name, product_path(product), class: 'product' %></h4>
            <hr>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="product-panel panel panel-default">
        <div class="panel-heading">
          <h3>Made in the USA!</h3>
        </div>
        <div class="panel-body">
          <% if @usa_made.any? %>
            <% @usa_made.each do |product| %>
              <h4><%= link_to product.name, product_path(product), class: 'product' %></h4>
            <% end %>
          <% else %>
            <h4>We currently do not carry any products made in the USA.</h4>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<h1>All of Our Products!</h1>
<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product_path(product), class: 'product' %> </li>
  <% end %>
</ul>

app/views/products/new.html.erb
<h1>Add a New Product!</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1> <%= @product.name %> <button class="btn btn-warning review-button"><%= link_to "Add Review", new_product_review_path(@product) %></button></h1>

<h3>Cost: $<%= @product.cost %>.00 </h3>
<h3>Country of Origin: <%= @product.origin %> </h3>

<h4>Reviews:</h4>

<% if @product.reviews.any? %>
  <% @product.reviews.each do |review| %>
    <div class="review panel panel-default">
      <div class="panel-heading">
        <strong> <%= review.author %> | Rating: <%= review.rating %> | <button class="btn btn-success"><%= link_to "Edit", edit_product_review_path(@product, review) %></button> </strong>
      </div>
      <div class="panel-body">
        <p> <%= review.content_body %> </p>
      </div>
    </div>
  <% end %>
<% else %>
  <h4>There are currently no reviews for this product!</h4>
<% end %>
<hr>
<button class="btn btn-success"><%= link_to "Edit", edit_product_path(@product) %></button>
<button class="btn btn-danger delete-button"><%= link_to "Delete", product_path(@product),
                               :data => {:confirm => "Are you sure?",
                                              :method => "delete"} %></button>

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product,@review] do |f| %>
  <div class="form-group">
    <%= f.label :author, class: "control-label"%>
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content_body, class: "control-label" %>
    <%= f.text_area :content_body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :rating, class: "control-label" %>
    <%= f.text_field :rating, class: "form-control" %>
  </div>
  <%= f.submit class: "btn" %>
<% end %>

app/views/reviews/edit.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product,@review] do |f| %>
  <div class="form-group">
    <%= f.label :author, class: "control-label"%>
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content_body, class: "control-label" %>
    <%= f.text_area :content_body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :rating, class: "control-label" %>
    <%= f.text_field :rating, class: "form-control" %>
  </div>
  <%= f.submit class: "btn" %>
<% end %>

app/views/reviews/new.html.erb
<h1>Add a Review for <%= @product.name %> </h1>

<%= render 'form' %>